version: 2.1
orbs: 
  heroku: circleci/heroku@1.2.6
jobs:
  push_image_on_heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: HEROKU_API_KEY=${HEROKU_API_KEY} heroku apps:create oc-lettings-ribeiro || true
      - run: |
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=${SECRET_KEY} -a oc-lettings-ribeiro
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set DEBUG=false -a oc-lettings-ribeiro
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set ALLOWED_HOSTS=${ALLOWED_HOSTS} -a oc-lettings-ribeiro
      - heroku/push-docker-image
      - heroku/release-docker-image
workflows:
  heroku_deploy:
    jobs:
      - push_image_on_heroku