version: 2.1
orbs: 
  heroku: circleci/heroku@1.2.6
jobs:
  push_image_on_heroku:
    executor: heroku/default
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - heroku/install
      - run: HEROKU_API_KEY=${HEROKU_API_KEY} heroku apps:create oc-lettings-ribeiro || true
      - run: |
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=${SECRET_KEY} -a oc-lettings-ribeiro
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set DEBUG=false -a oc-lettings-ribeiro
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set ALLOWED_HOSTS=${ALLOWED_HOSTS} -a oc-lettings-ribeiro
      - run: docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
      - run: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web -a oc-lettings-ribeiro
      - run: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a oc-lettings-ribeiro
workflows:
  heroku_deploy:
    jobs:
      - push_image_on_heroku